let employees = [{ "id": 1, "first_name": "Rozele", "email": "rgoodison0@reverbnation.com", "gender": "Agender" },
{ "id": 2, "first_name": "Justina", "email": "jmidner1@latimes.com", "gender": "Female" },
{ "id": 3, "first_name": "Lorry", "email": "ljewson2@ycombinator.com", "gender": "Male" },
{ "id": 4, "first_name": "Em", "email": "ethatcher3@ft.com", "gender": "Male" },
{ "id": 5, "first_name": "Rollie", "email": "rgammon4@cdbaby.com", "gender": "Male" },
{ "id": 6, "first_name": "Lowrance", "email": "lszymanowicz5@deliciousdays.com", "gender": "Male" },
{ "id": 7, "first_name": "Fancie", "email": "fpicard6@google.com.au", "gender": "Female" },
{ "id": 8, "first_name": "Biddy", "email": "bbartunek7@cdc.gov", "gender": "Female" },
{ "id": 9, "first_name": "Inglis", "email": "imccaughen8@weibo.com", "gender": "Genderfluid" },
{ "id": 10, "first_name": "Emalia", "email": "edowne9@google.com.hk", "gender": "Female" },
{ "id": 11, "first_name": "Serge", "email": "sdunsa@unc.edu", "gender": "Male" },
{ "id": 12, "first_name": "Rhodia", "email": "rfetherstonhaughb@exblog.jp", "gender": "Female" },
{ "id": 13, "first_name": "Feliza", "email": "fbartloszc@woothemes.com", "gender": "Female" },
{ "id": 14, "first_name": "Freddie", "email": "ftrottd@fastcompany.com", "gender": "Male" },
{ "id": 15, "first_name": "Sapphira", "email": "sdonete@myspace.com", "gender": "Female" },
{ "id": 16, "first_name": "Ruthanne", "email": "rgajownikf@live.com", "gender": "Female" },
{ "id": 17, "first_name": "Merrily", "email": "mwestreyg@ebay.com", "gender": "Female" },
{ "id": 18, "first_name": "Hayyim", "email": "htripneyh@nationalgeographic.com", "gender": "Male" },
{ "id": 19, "first_name": "Shari", "email": "sbettisi@go.com", "gender": "Female" },
{ "id": 20, "first_name": "Rianon", "email": "rcollynsj@howstuffworks.com", "gender": "Female" },
{ "id": 21, "first_name": "Sibeal", "email": "smandyk@ft.com", "gender": "Female" },
{ "id": 22, "first_name": "Cathee", "email": "ccorsanl@mtv.com", "gender": "Female" },
{ "id": 23, "first_name": "Delcina", "email": "dghestm@ehow.com", "gender": "Female" },
{ "id": 24, "first_name": "Michelle", "email": "mmcallastern@baidu.com", "gender": "Female" },
{ "id": 25, "first_name": "Chas", "email": "cfebreo@plala.or.jp", "gender": "Male" },
{ "id": 26, "first_name": "Cullin", "email": "cbelhommep@sciencedaily.com", "gender": "Genderfluid" },
{ "id": 27, "first_name": "Lotta", "email": "lwreathq@princeton.edu", "gender": "Female" },
{ "id": 28, "first_name": "Lambert", "email": "ltessierr@tmall.com", "gender": "Male" },
{ "id": 29, "first_name": "Heddie", "email": "hellers@chron.com", "gender": "Female" },
{ "id": 30, "first_name": "Kev", "email": "kshillomt@slashdot.org", "gender": "Genderfluid" },
{ "id": 31, "first_name": "Lorette", "email": "lcrosbieu@constantcontact.com", "gender": "Female" },
{ "id": 32, "first_name": "Steve", "email": "sdaneletv@ifeng.com", "gender": "Male" },
{ "id": 33, "first_name": "Venita", "email": "vworsnapw@lulu.com", "gender": "Female" },
{ "id": 34, "first_name": "Haze", "email": "hpriestmanx@deviantart.com", "gender": "Male" },
{ "id": 35, "first_name": "Rachele", "email": "roroany@house.gov", "gender": "Female" },
{ "id": 36, "first_name": "Broderic", "email": "bgallawayz@mashable.com", "gender": "Male" },
{ "id": 37, "first_name": "Angelle", "email": "adobell10@marriott.com", "gender": "Female" },
{ "id": 38, "first_name": "Evvy", "email": "esymcoxe11@hostgator.com", "gender": "Female" },
{ "id": 39, "first_name": "Lyssa", "email": "lortells12@ning.com", "gender": "Female" },
{ "id": 40, "first_name": "Ken", "email": "klaird13@sourceforge.net", "gender": "Male" },
{ "id": 41, "first_name": "Aigneis", "email": "adimitrijevic14@bloglovin.com", "gender": "Non-binary" },
{ "id": 42, "first_name": "Ransell", "email": "rcullerne15@shareasale.com", "gender": "Male" },
{ "id": 43, "first_name": "Zedekiah", "email": "zfilipychev16@princeton.edu", "gender": "Male" },
{ "id": 44, "first_name": "Bethena", "email": "bnolton17@sciencedirect.com", "gender": "Female" },
{ "id": 45, "first_name": "Bevvy", "email": "braiston18@nature.com", "gender": "Female" },
{ "id": 46, "first_name": "Stirling", "email": "sdinsale19@surveymonkey.com", "gender": "Male" },
{ "id": 47, "first_name": "Shannon", "email": "sdeknevet1a@yahoo.com", "gender": "Female" },
{ "id": 48, "first_name": "Haslett", "email": "hbruniges1b@mac.com", "gender": "Male" },
{ "id": 49, "first_name": "Salmon", "email": "sacosta1c@wikimedia.org", "gender": "Male" },
{ "id": 50, "first_name": "Marjory", "email": "mguerrin1d@bbc.co.uk", "gender": "Female" },
{ "id": 1, "first_name": "Rozele", "email": "rgoodison0@reverbnation.com", "gender": "Agender" },
{ "id": 2, "first_name": "Justina", "email": "jmidner1@latimes.com", "gender": "Female" },
{ "id": 3, "first_name": "Lorry", "email": "ljewson2@ycombinator.com", "gender": "Male" },
{ "id": 4, "first_name": "Em", "email": "ethatcher3@ft.com", "gender": "Male" },
{ "id": 5, "first_name": "Rollie", "email": "rgammon4@cdbaby.com", "gender": "Male" },
{ "id": 6, "first_name": "Lowrance", "email": "lszymanowicz5@deliciousdays.com", "gender": "Male" },
{ "id": 7, "first_name": "Fancie", "email": "fpicard6@google.com.au", "gender": "Female" },
{ "id": 8, "first_name": "Biddy", "email": "bbartunek7@cdc.gov", "gender": "Female" },
{ "id": 9, "first_name": "Inglis", "email": "imccaughen8@weibo.com", "gender": "Genderfluid" },
{ "id": 10, "first_name": "Emalia", "email": "edowne9@google.com.hk", "gender": "Female" },
{ "id": 11, "first_name": "Serge", "email": "sdunsa@unc.edu", "gender": "Male" },
{ "id": 12, "first_name": "Rhodia", "email": "rfetherstonhaughb@exblog.jp", "gender": "Female" },
{ "id": 13, "first_name": "Feliza", "email": "fbartloszc@woothemes.com", "gender": "Female" },
{ "id": 14, "first_name": "Freddie", "email": "ftrottd@fastcompany.com", "gender": "Male" },
{ "id": 15, "first_name": "Sapphira", "email": "sdonete@myspace.com", "gender": "Female" },
{ "id": 16, "first_name": "Ruthanne", "email": "rgajownikf@live.com", "gender": "Female" },
{ "id": 17, "first_name": "Merrily", "email": "mwestreyg@ebay.com", "gender": "Female" },
{ "id": 18, "first_name": "Hayyim", "email": "htripneyh@nationalgeographic.com", "gender": "Male" },
{ "id": 19, "first_name": "Shari", "email": "sbettisi@go.com", "gender": "Female" },
{ "id": 20, "first_name": "Rianon", "email": "rcollynsj@howstuffworks.com", "gender": "Female" },
{ "id": 21, "first_name": "Sibeal", "email": "smandyk@ft.com", "gender": "Female" },
{ "id": 22, "first_name": "Cathee", "email": "ccorsanl@mtv.com", "gender": "Female" },
{ "id": 23, "first_name": "Delcina", "email": "dghestm@ehow.com", "gender": "Female" },
{ "id": 24, "first_name": "Michelle", "email": "mmcallastern@baidu.com", "gender": "Female" },
{ "id": 25, "first_name": "Chas", "email": "cfebreo@plala.or.jp", "gender": "Male" },
{ "id": 26, "first_name": "Cullin", "email": "cbelhommep@sciencedaily.com", "gender": "Genderfluid" },
{ "id": 27, "first_name": "Lotta", "email": "lwreathq@princeton.edu", "gender": "Female" },
{ "id": 28, "first_name": "Lambert", "email": "ltessierr@tmall.com", "gender": "Male" },
{ "id": 29, "first_name": "Heddie", "email": "hellers@chron.com", "gender": "Female" },
{ "id": 30, "first_name": "Kev", "email": "kshillomt@slashdot.org", "gender": "Genderfluid" },
{ "id": 31, "first_name": "Lorette", "email": "lcrosbieu@constantcontact.com", "gender": "Female" },
{ "id": 32, "first_name": "Steve", "email": "sdaneletv@ifeng.com", "gender": "Male" },
{ "id": 33, "first_name": "Venita", "email": "vworsnapw@lulu.com", "gender": "Female" },
{ "id": 34, "first_name": "Haze", "email": "hpriestmanx@deviantart.com", "gender": "Male" },
{ "id": 35, "first_name": "Rachele", "email": "roroany@house.gov", "gender": "Female" },
{ "id": 36, "first_name": "Broderic", "email": "bgallawayz@mashable.com", "gender": "Male" },
{ "id": 37, "first_name": "Angelle", "email": "adobell10@marriott.com", "gender": "Female" },
{ "id": 38, "first_name": "Evvy", "email": "esymcoxe11@hostgator.com", "gender": "Female" },
{ "id": 39, "first_name": "Lyssa", "email": "lortells12@ning.com", "gender": "Female" },
{ "id": 40, "first_name": "Ken", "email": "klaird13@sourceforge.net", "gender": "Male" },
{ "id": 41, "first_name": "Aigneis", "email": "adimitrijevic14@bloglovin.com", "gender": "Non-binary" },
{ "id": 42, "first_name": "Ransell", "email": "rcullerne15@shareasale.com", "gender": "Male" },
{ "id": 43, "first_name": "Zedekiah", "email": "zfilipychev16@princeton.edu", "gender": "Male" },
{ "id": 44, "first_name": "Bethena", "email": "bnolton17@sciencedirect.com", "gender": "Female" },
{ "id": 45, "first_name": "Bevvy", "email": "braiston18@nature.com", "gender": "Female" },
{ "id": 46, "first_name": "Stirling", "email": "sdinsale19@surveymonkey.com", "gender": "Male" },
{ "id": 47, "first_name": "Shannon", "email": "sdeknevet1a@yahoo.com", "gender": "Female" },
{ "id": 48, "first_name": "Haslett", "email": "hbruniges1b@mac.com", "gender": "Male" },
{ "id": 49, "first_name": "Salmon", "email": "sacosta1c@wikimedia.org", "gender": "Male" },
{ "id": 50, "first_name": "Marjory", "email": "mguerrin1d@bbc.co.uk", "gender": "Female" }]

let display_Data = () => {
    let rows = ""
    employees.forEach((employee) => {
        rows = rows + `<tr>
                <td>${employee.id}</td>
                <td>${employee.first_name}</td>
                <td>${employee.email}</td>
                <td>${employee.gender}</td>
            </tr>`
    })
    document.getElementById('tbody_Data').innerHTML = rows
}